CREATE TABLE members (
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(50) DEFAULT NULL,
	last_name varchar(50) DEFAULT NULL,
	email varchar(255) NOT NULL,
	country varchar(255) DEFAULT NULL,
	created timestamp DEFAULT current_timestamp,
	status smallint NULL DEFAULT '1'
);